[PRMT-1009] Setup GoCD notifications to google chat

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -4,6 +4,17 @@ set -Eeo pipefail
 
 NHS_SERVICE=gocd
 AWS_REGION=eu-west-2
+AWS_DEFAULT_REGION=$AWS_REGION
+
+function get_aws_ssm_secret {
+  secret_id=$1
+  json=$(dojo "aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id")
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+    exit 5
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
 
 function tf_plan {
   operation=$1
@@ -102,17 +113,24 @@ case "${command}" in
       ;;
   _provision)
     check_env
+    if [ -z "${GOOGLE_CHAT_WEBHOOK}" ]; then
+      echo "GOOGLE_CHAT_WEBHOOK must be set"
+      exit 5
+    fi
     sudo pip install yasha #FIXME: add yasha in the dojo image
     yasha --variables terraform/tf-out.json -o ansible/inventory/${NHS_ENVIRONMENT}.ini ansible/inventory/template.ini.j2
     mkdir -p ansible/group_vars
     cat << EOF > ansible/group_vars/${NHS_ENVIRONMENT}.yml
 # This file is generated
 env: ${NHS_ENVIRONMENT}
+google_chat_webhook: ${GOOGLE_CHAT_WEBHOOK}
 EOF
     ansible-playbook -i ansible/inventory/${NHS_ENVIRONMENT}.ini ansible/site.yml
     ;;
   provision)
     check_env
+    GOOGLE_CHAT_WEBHOOK=$(get_aws_ssm_secret "/NHS/GoCD/${NHS_ENVIRONMENT}/google-chat-webhook")
+    export GOOGLE_CHAT_WEBHOOK
     dojo -c Dojofile-ansible "./tasks _provision"
     ;;
   generate_ssl_certs)
